version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:30"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
