require:
  - rubocop-performance
  - rubocop/cop/cobalt

AllCops:
  NewCops: enable

Naming/MethodName:
  EnforcedStyle: snake_case

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/DotPosition:
  EnforcedStyle: leading

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Cobalt/InsecureHashAlgorithm:
  Enabled: true
