require:
  - rubocop-rspec

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

RSpec/ExampleLength:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/Rails/InferredSpecType:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleMemoizedHelpers:
  Max: 17

RSpec/NamedSubject:
  Enabled: true

RSpec/NestedGroups:
  Max: 5

# This cop does not correctly detect that RSwag creates
# extra contexts, reporting false positives for those tests
RSpec/ScatteredSetup:
  Exclude:
    - '{components/*/,}spec/api/**/*'

RSpec/VariableName:
  AllowedPatterns:
    - ^Authorization
    - '\[\]$' # For array parameters in rswag like `let(:'<parameter_name>[]')`
